server:
  port: 8081

spring:
  application:
    name: acme-financial-ui
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411

logging:
  level:
    org.springframework.cloud.sleuth: DEBUG
debug: true